"""empty message

Revision ID: 2f58434817b4
Revises: 
Create Date: 2022-07-08 22:25:02.436987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f58434817b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('text_x_pos', sa.Integer(), nullable=True),
    sa.Column('text_y_pos', sa.String(length=64), nullable=True),
    sa.Column('target_width_ratio', sa.Float(), nullable=True),
    sa.Column('sponge_the_text', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_request')
    # ### end Alembic commands ###
