"""empty message

Revision ID: c1903cc0bc79
Revises: 493f92791fbf
Create Date: 2022-07-08 23:04:10.807172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1903cc0bc79'
down_revision = '493f92791fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_request', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_request', 'timestamp')
    # ### end Alembic commands ###
