"""empty message

Revision ID: c4ab0518747c
Revises: 322be74fee7c
Create Date: 2022-07-10 01:49:30.588835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ab0518747c'
down_revision = '322be74fee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('requests_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'requests_per_day')
    # ### end Alembic commands ###
